version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
        - ./pgdata:/var/lib/postgresql/data
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: pgadmin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "8080:80"
  jupyter:
    build: .
    container_name: jupyter_container
    image: me/jupyter
    ports: 
      - "8888:8888"
    volumes:
      - ./notebooks:/src/notebooks
# volumes: 
#   pgdata: ./pgdata